// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOapSSDLgxbuBAubeIx4m7JLGnVJTYkhM',
    appId: '1:754599152402:web:0ea2d8f21d9b574d2b01cb',
    messagingSenderId: '754599152402',
    projectId: 'banco-de-dados-de-apicultores',
    authDomain: 'banco-de-dados-de-apicultores.firebaseapp.com',
    storageBucket: 'banco-de-dados-de-apicultores.appspot.com',
    measurementId: 'G-D40R7GR5B7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtl3mCY127XShagmHO8pdWWnfEXJZIYxw',
    appId: '1:754599152402:android:2a83b112e70b189c2b01cb',
    messagingSenderId: '754599152402',
    projectId: 'banco-de-dados-de-apicultores',
    storageBucket: 'banco-de-dados-de-apicultores.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHUKceNPf2795gs95gJItITc0Hk4oq9uo',
    appId: '1:754599152402:ios:eedc59bce8ceea4e2b01cb',
    messagingSenderId: '754599152402',
    projectId: 'banco-de-dados-de-apicultores',
    storageBucket: 'banco-de-dados-de-apicultores.appspot.com',
    iosBundleId: 'com.example.proposlisandoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHUKceNPf2795gs95gJItITc0Hk4oq9uo',
    appId: '1:754599152402:ios:cc50e2c39615c1d62b01cb',
    messagingSenderId: '754599152402',
    projectId: 'banco-de-dados-de-apicultores',
    storageBucket: 'banco-de-dados-de-apicultores.appspot.com',
    iosBundleId: 'com.example.proposlisandoApp.RunnerTests',
  );
}
